### ISSUE TITLE
Toevoegen veld 'rapporttype' aan tabel ispiegel_controle

### ISSUE THREAD

**Issue by htenhave** [VNG-Realisatie/i-Spiegel#10]
Dit veld moet vervolgens bij het draaien, net als bij vergelijking, worden gekopieerd naar ispiegel_output.

**Comment by EduardWitteveen** [comment]
Dit veldtype komt voor in 3 tabellen, namelijk in VERGELIJING, CONTROLE en in OUTPUT.
 
Dit zijn de uit te voeren wijzigingen:
 
alter table ISPIEGEL_VERGELIJKING
add (RAPPORTTYPE number(38,0));
 
alter table ISPIEGEL_CONTROLE
add (RAPPORTTYPE number(38,0));
 
alter table ISPIEGEL_OUTPUT
add (RAPPORTTYPE number(38,0));
 
Mocht je ze nog niet hebben: in de tabellen VERGELIJKING en CONTROLE heb je daarnaast ook nog de velden ROLCOGNOSBEKIJKANALYSE en ROLCOGNOSBEKIJKREFERENTIE nodig (zie bijlage).
 
Daarnaast heb ik nog wat indexen toegevoegd ter verhoging van de performance van rapport 3 Bevindingen. Is het mogelijk om eens te testen of er verschil zit in de performance zonder en met deze indexering?
 
Het lijkt mij praktisch om de bijlage bij de uitleveringte doen zodat iedereen na kan gaan of hij de juiste (nieuwe) velden in zijn/haar database heeft. Daarom de vraag of de bijlage aanpassingen… zo duidelijk genoeg is.
 
Daarnaast nog een scriptje dat nodig is totdat Eduard ttijd heeft gehad om de .exe aan te passen op het kopiëren van het rapporttype naar tabel OUTPUT.
