### ISSUE TITLE
Meervoudige uitval wordt onterecht ook meervoudig weg geschreven (was: iSpiegel kan niet (op)tellen)

### ISSUE THREAD

**Issue by htenhave** [VNG-Realisatie/i-Spiegel#18]
Het totaal aantal afwijkende bevindingen wordt in de logging niet goed opgeteld.

Voorbeelden
FIN.Persoon-GD.FIN.Persoon_Schiermonnikoog                  96% gelijk #1233 afwijkend #32 mist #8(adding #65 outputlines )
SD_Regie.Persoon-GD.SD_Regie.Persoon_Schiermonnikoog        36% gelijk #29 afwijkend #4 mist #46(adding #56 outputlines )
WOZ.Persoon-GD.WOZ.Persoon_Schiermonnikoog                  98% gelijk #1139 afwijkend #10 mist #3(adding #17 outputlines )

Regel 1: #afwijkend is 32, # missend is 8. Totaal is 40. Maar er worden 65 regels weggeschreven.
Regel 2: 29 + 4 = 46?
Regel 3: 10 + 3 = 17?

Het totaal aantal weggeschreven bevindingen klopt. Idem voor mist.

Conclusie: fout in optelling afwijkende bevindingen.

**Comment by htenhave** [comment]
Conclusie blijkt verkeerd te zijn. Reden: er vind meervoudige uitval op het zelfde record plaats. Bij de telling wordt alleen de 1e keer geregistreerd, maar bij het wegschrijven resulteert het wel in meerdere bevindingen, wat juist niet de bedoeling is (iSpiegel hoort met vergelijken te stoppen na 1e constatering van verschil)..

Zie schermafdrukken
![Meervoudige uitval iSpiegel 01](https://user-images.githubusercontent.com/38486364/155957069-5a283bee-85bc-4809-a8d5-9c92d35f4a16.jpg)
![Meervoudige uitval iSpiegel 02](https://user-images.githubusercontent.com/38486364/155957071-e9be099e-af55-4daa-87e8-2325d1584612.jpg)
.

**Comment by htenhave** [comment]
Controle 1
Aangezien er geen versienummer in de iSpiegel zit: hoe controleer ik of ik de laatste versie van de iSpiegel gebruik? Als datum zie ik 16-3-'21 maar dat kan ook de kopieerdatum zijn.

**Comment by htenhave** [comment]
Reden om niet meervoudig weg te schrijven is om te voorkomen dat de 'hersteller' het zelfde record meerdere keren moet bekijken terwijl dit bij de 1e keer mogelijk al is opgelost.
Het argument voor meervoudig wegschrijven 'voor het geval er nog meer afwijkingen in zitten' is ondervangen door in de rapportage van de bevinding niet alleen de uitvalreden te laten zien maar ook het complete record zodat op die manier toch te zien is of er nog andere uitvalredenen zijn.

**Comment by EduardWitteveen** [comment]
Kan in de nieuwe versie worden geconfigureerd met de configuratie-parameter: output_nomatch_reportall
Deze staat default op false
